# STAGES
stages: 
    - test
    - quality
    - build
    - deploy

# JOBS
test-job:  
    stage: test
    script:
        - echo "--------------- METEOR TEST ---------------"
        - echo "*** Current Repo ***"
        - pwd
        - cd src/simple-todos/step12
        - echo "*** Install Meteor ***"
        - curl https://install.meteor.com/ | sh
        - echo "*** Meteor Commands***"
        - meteor npm install --allow-superuser
        - meteor test --once --driver-package meteortesting:mocha --allow-superuser
    only:
        - develop

quality-job:
    stage: quality
    script:
        - echo "------------- METEOR QUALITY -------------"
        - echo "*** Current Repo ***"
        - pwd
        - cd src/simple-todos/step12
        - echo "*** Install Meteor ***"
        - curl https://install.meteor.com | sh
        - echo "*** Meteor Commands ***"
        - meteor npm install --allow-superuser
        - meteor npm run-script lint --allow-superuser

build-job:
    stage: build
    script:
        - echo "------------- METEOR BUILD -------------"
        - echo "*** Current Repo ***"
        - pwd
        - cd src/simple-todos/step12
        - echo "*** Install Meteor ***"
        - curl https://install.meteor.com | sh
        - echo "*** Meteor Commands ***"
        - meteor npm install --allow-superuser
        - meteor npm run-script build --allow-superuser

deploy-dev-job:
    stage: deploy
    script: 
        - "Deploys some code from the $CI_COMMIT_BRANCH branch on the dev environment."
    only:
        - develop
    allow_failure: false

deploy-prod-job:
    stage: deploy
    script:
        - "Deploys some code from the $CI_COMMIT_BRANCH branch on the prod environment."
    only:
        - master
    allow_failure: false